README.mdに構成図を学習記録をついかしました、各md.の記法に誤りがあったので修正しました。
ReoNakamura/RaiseTech pull request #12
Opened 2024-08-23 10:28 UTC by ReoNakamura

GitHub上では表示されている画像がローカルでは表示されていなかったので、記法を修正しました。
README. mdの内容を更新いたしましたので、ご確認よろしくお願いいたします

2024-08-24 14:44 UTC, MasatoshiMizumoto requested changes
拝見しました！
コメント入れましたのでご対応お願いします！！

2024-08-24 14:44 UTC, MasatoshiMizumoto commented on README.md
- RaiseTechのコース名
  - AWSフルコースです
- 構成図
  - CloudFormationはリージョナルサービスです
  - IGWはVPCサービスです
  - ALBはELBと異なります、所属サブネットがあります
  - Internetアイコンが形状異なる気がしますので公式の図面をご確認ください

2024-08-25 00:47 UTC, ReoNakamura commented on README.md
README.mdのコース名と構成図を修正いたしました。ご確認お願いいたします。
lecture13.mdの構成図も差し替えました。

2024-08-25 04:39 UTC, MasatoshiMizumoto commented on README.md
ありがとうございます！すいませんが追加で以下お願いします！

- CloudFormationの名称誤記
- リージョンがモノクロスタイルなのでカラー版に
- AWS CloudはAWSのロゴのほうを原則推奨なのでそちらに変更
- サービスアイコンのサイズにばらつきがあるので統一（構成図は同じ正方形アイコンならサイズは統一したほうが見やすいです）

細かい指摘がありますが、中身が合っているからこそできる指摘なので、ポジティブに捉えていただければ！

2024-08-25 05:59 UTC, ReoNakamura commented on README.md
構成図の指摘された箇所を修正いたしました！
もう一度ご確認お願いいたします。

2024-08-25 06:06 UTC, ReoNakamura commented on README.md
構成図の指摘された箇所を修正いたしました！
もう一度、ご確認お願いいたします。

2024-08-25 08:07 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2024-08-25 08:16 UTC, merged