Lecture04
ReoNakamura/RaiseTech pull request #4
Opened 2023-08-03 13:04 UTC by ReoNakamura

お疲れ様です。ご確認お願いします

2023-08-03 16:07 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2023-08-03 16:07 UTC, MasatoshiMizumoto commented on lecture04.md
> +
スタイリング反映されてないですね！

2023-08-03 16:07 UTC, MasatoshiMizumoto commented on lecture04.md
> +osを間違えたり、パブリックIPアドレスを作らない設定して上手く接続できずにいた。
段落は改行無視されるので、行が必須ならリスト形式にするなど工夫してみてください！

2023-08-06 00:13 UTC, ReoNakamura commented on lecture04.md
> +osを間違えたり、パブリックIPアドレスを作らない設定して上手く接続できずにいた。
修正しました！

2023-08-06 10:40 UTC, MasatoshiMizumoto approved these changes
LGTM!
今後は提出しないファイルが含まれないようにしてください！

2023-08-06 11:14 UTC, ReoNakamura commented
> LGTM! 今後は提出しないファイルが含まれないようにしてください！

2023-08-06 11:16 UTC, ReoNakamura commented
はい！分かりました！

2023-08-06 11:16 UTC, merged