Lecture10
ReoNakamura/RaiseTech pull request #8
Opened 2023-12-16 12:19 UTC by ReoNakamura

第10回のレポートを提出いたします。よろしくお願いいたします。

2023-12-16 15:49 UTC, MasatoshiMizumoto requested changes
コメント入れておりますので対応お願いいたします！

2023-12-16 15:49 UTC, MasatoshiMizumoto commented on lecture10-image/CF-Template/VPC.YAML
> +       Fn::Sub: ${NameBase}-privateSubnet2c
- Export名の変更
  - この変数にはIDが入ってますか？名前が入ってますか？
  - 何が入っているのか名称から判断付かないので、分かりやすくしたほうが良いかと思います！
- 最終行警告の解消
  - PRのFiles Changedをご自身でご確認ください！

2023-12-16 15:49 UTC, MasatoshiMizumoto commented on lecture10-image/CF-Template/EC2-RDS.YAML
> +        Value: !Sub ${NameBase}-RDS
- 最終行警告の解消
  - PRのFiles Changedをご自身でご確認ください！

2023-12-16 15:49 UTC, MasatoshiMizumoto commented on lecture10-image/CF-Template/EC2-RDS.YAML
> +    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
これは最新のAMIが適用されて良い方法ではあるのですが、一方で変動値が入っているので、
極端な場合、昨日デプロイしたスタックと今日デプロイしたスタックのAMI-IDが異なることがあり得ます。
理解いただいたうえで使ってください！（直さなくても大丈夫ですが、他のエンジニアに指摘されたら説明できるようにしておいてください）

2023-12-18 02:39 UTC, ReoNakamura commented on lecture10-image/CF-Template/EC2-RDS.YAML
> +    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
分かりました！

2023-12-19 12:29 UTC, ReoNakamura commented
修正しました！ご確認おねがいします。

2023-12-19 13:26 UTC, MasatoshiMizumoto approved these changes
LGTM!

2024-03-31 11:29 UTC, merged